# Generated by Django 2.1.2 on 2019-03-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporter', '0016_auto_20190317_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_id', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('material', models.CharField(default='ferrous', max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Report', verbose_name='the related report')),
            ],
        ),
    ]
