# Generated by Django 2.1.2 on 2019-03-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='react_id',
            new_name='react_component_id',
        ),
    ]
