# Generated by Django 2.1.2 on 2019-03-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20190318_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='material',
        ),
    ]
