# Generated by Django 2.1.1 on 2018-10-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0004_auto_20181002_0625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
