# Generated by Django 2.1.1 on 2018-10-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0007_parameter_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
