# Generated by Django 2.1.1 on 2018-11-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0009_parameter'),
    ]

    operations = [
        migrations.RunSQL('CREATE FUNCTION "cylinder_t"(P float, S float, D float, C_A float, E float default 1.0) RETURNS float AS $$ \
                            BEGIN \
                            RETURN (P * (D + 2.0 * C_A) / 2.0) / (S * 1000 * E - 0.6 * P) + C_A; \
                            END; $$ \
                            LANGUAGE PLPGSQL'),
    ]
