apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vessel-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: vessel-backend
    spec:
      containers:
        - name: vessel-backend-container
          image: "gcr.io/kuber-test-263901/vessel-backend:20.01.17.v1.0"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: vessel-env