steps:
  #step 1
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/vessel-backend:latest || exit 0"]
  #step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/vessel-backend:$TAG_NAME",
        "-t",
        "gcr.io/$PROJECT_ID/vessel-backend:latest",
        ".",
      ]
  #step 3
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "k8s/"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=calcgen-cluster"
  #step 4
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment",
        "vessel-backend",
        "vessel-backend=gcr.io/$PROJECT_ID/vessel-backend:$TAG_NAME",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=calcgen-cluster"
# push images to Google Container Registry with tags
images:
  [
    "gcr.io/$PROJECT_ID/vessel-backend:$TAG_NAME",
    "gcr.io/$PROJECT_ID/vessel-backend:latest",
  ]
