apiVersion: v1
kind: ConfigMap
metadata:
  name: vessel-env
  namespace: default
data:
  SECRET_KEY: "vna)l$8h17el#gu!a(fh8bb177)!o#j%y@h9xu$vad1)s+%4m5"
  DEBUG: "True"
  ALLOWED_HOSTS: '["vesselexpress-backend.appspot.com","vesselexpress.calcgen.com","www.vesselexpress-backend.appspot.com","www.vesselexpress.calcgen.com","*"]'
  DB_HOST: "/cloudsql/calcgen:us-central1:calcgen-db"
  DB_PORT: "5432"
  DB_NAME: "calcgen-vessel"
  DB_USER: "calcgen-vessel"
  DB_PASSWORD: "shrestha"
  SECURE_SSL_REDIRECT: "False"
  SESSION_COOKIE_SECURE: "False"
  CSRF_COOKIE_SECURE: "False"
  STATIC_URL: "https://storage.googleapis.com/calcgen.appspot.com/vessel/static/"
  DEFAULT_FROM_EMAIL: "grunze1212@gmail.com"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_HOST_PASSWORD: "vphfhnbyxwfsmqxs"
  EMAIL_HOST_USER: "grunze1212@gmail.com"
  SERVER_EMAIL: "grunze1212@gmail.com"
  OIDC_RP_CLIENT_ID: "121026"
  OIDC_RP_CLIENT_SECRET: "299b2addc696d30f3db8313db4ae05e8f1e2fcce619ad84f55dbcd88"
  OIDC_RP_PROVIDER_END_SESSION_ENDPOINT: "https://calcgen.appspot.com/auth/end-session/"
  OIDC_RP_PROVIDER_ENDPOINT: "https://calcgen.appspot.com/auth/"
  OIDC_RP_AUTHENTICATION_REDIRECT_URI: "https://ve-dot-calcgen.appspot.com/builder"
  LOGOUT_REDIRECT_URL: "https://calcgen.appspot.com"
  PRODUCTION: "True"
