# Generated by Django 2.1.3 on 2019-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_size', models.CharField(max_length=255)),
                ('od_inch', models.FloatField(default=0.0)),
                ('id_inch', models.FloatField(default=0.0)),
                ('schedules', models.CharField(max_length=255)),
                ('wall_inch', models.FloatField(default=0.0)),
                ('est_wt', models.FloatField(default=0.0)),
            ],
        ),
    ]
