# Generated by Django 2.1.3 on 2019-02-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asme', '0002_pipingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipingschedule',
            name='pipe_size',
            field=models.FloatField(default=0.0),
        ),
    ]
