# Generated by Django 2.1.3 on 2019-03-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asme', '0004_auto_20190226_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='maximumallowablestress',
            name='density',
            field=models.FloatField(default=0.0),
        ),
    ]
