# Generated by Django 2.1.3 on 2019-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asme', '0005_maximumallowablestress_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzledata',
            name='base_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzledata',
            name='base_weight_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzledata',
            name='neck_thickness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzledata',
            name='nut_relief_diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzledata',
            name='nut_relief_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzledata',
            name='nut_stop_diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzledata',
            name='weight_per_one_inch',
            field=models.FloatField(default=0.0),
        ),
    ]
