# Generated by Django 2.1.3 on 2019-03-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asme', '0006_auto_20190311_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipingschedule',
            old_name='est_wt',
            new_name='est_wt_pipe',
        ),
    ]
