# Generated by Django 2.1.3 on 2019-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asme', '0007_auto_20190311_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzledata',
            name='raised_face_thickness',
            field=models.FloatField(default=0.0),
        ),
    ]
