# Generated by Django 2.1.1 on 2018-10-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0002_auto_20181002_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='thickness',
        ),
    ]
