# Generated by Django 2.1.1 on 2018-10-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0003_remove_parameter_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='strength',
            field=models.FloatField(default=1),
        ),
    ]
