# Generated by Django 2.1.3 on 2019-02-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cylinder', '0010_auto_20181101_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
