apiVersion: apps/v1
kind: Deployment
metadata:
  name: vessel-backend
  labels:
    app: vessel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vessel-backend
  template:
    metadata:
      labels:
        app: vessel-backend
    spec:
      containers:
        - name: vessel-backend
          image: "gcr.io/kuber-test-263901/vessel-backend:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 40m
          envFrom:
            - configMapRef:
                name: vessel-env
          env:
            # [START cloudsql_secrets]
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-vessel
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-vessel
                  key: password
            # [END cloudsql_secrets]
        - image: gcr.io/cloudsql-docker/gce-proxy:1.16
          name: cloudsql-proxy
          resources:
            requests:
              cpu: 40m
          command:
            [
              "/cloud_sql_proxy",
              "--dir=/cloudsql",
              "-instances=calcgen:us-central1:calcgen-db=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
