# Generated by Django 2.1.2 on 2019-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(max_length=50)),
                ('location', models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/test_workspace/pressure-vessel/static/reports/')),
                ('location_state', models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/test_workspace/pressure-vessel/static/states/')),
                ('author', models.CharField(default='shovan', max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
