# Generated by Django 2.1.2 on 2019-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/test_workspace/vesselexpress-backendreports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_state',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/test_workspace/vesselexpress-backendstates/'),
        ),
    ]
