# Generated by Django 2.1.2 on 2019-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='model',
            field=models.CharField(default='shovan', max_length=100),
        ),
    ]
