# Generated by Django 2.1.2 on 2019-08-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20190819_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/test_workspace/vesselexpress-backend/reports'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_state',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/test_workspace/vesselexpress-backend/states'),
        ),
    ]
