# Generated by Django 2.1.2 on 2019-02-05 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_report_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cylinderstate',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Report', verbose_name='the related report'),
        ),
    ]
