# Generated by Django 2.1.2 on 2019-09-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20190825_0339'),
        ('reporter', '0003_auto_20190901_0651'),
    ]

    operations = [
    ]
