# Generated by Django 2.1.3 on 2019-03-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_cylinderstate_t_inter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, path='/home/grunz/Desktop/workspace/Pressure_Vessel/pressure_old/static/reports/'),
        ),
    ]
