# Generated by Django 2.1.3 on 2019-03-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20190303_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(default='shovan', max_length=101),
        ),
    ]
