# Generated by Django 2.1.3 on 2019-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0012_auto_20190310_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(default='shovan', max_length=255),
        ),
    ]
