# Generated by Django 2.1.3 on 2019-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_auto_20190310_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(default='shovan', max_length=100),
        ),
    ]
