# Generated by Django 2.1.2 on 2019-03-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0015_auto_20190317_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/calcgen2/pressureVessel/static/reports/'),
        ),
    ]
