# Generated by Django 2.1.2 on 2019-03-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_auto_20190317_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinderstate',
            name='report',
        ),
        migrations.DeleteModel(
            name='NozzleState',
        ),
        migrations.DeleteModel(
            name='CylinderState',
        ),
    ]
