# Generated by Django 2.1.3 on 2019-03-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_cylinderstate_component_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinderstate',
            name='component_id',
        ),
    ]
