# Generated by Django 2.1.3 on 2019-03-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('reporter', '0017_remove_cylinderstate_component_id'),
        ('reporter', '0017_auto_20190318_0714'),
    ]

    operations = [
    ]
