# Generated by Django 2.1.2 on 2019-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0019_auto_20190325_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/calcgen2/pressureVessel/static/reports/'),
        ),
    ]
