# Generated by Django 2.1.3 on 2019-03-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0020_auto_20190326_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/grunz/Desktop/workspace/Pressure_Vessel/pressure_old/static/reports/'),
        ),
    ]
