# Generated by Django 2.1.2 on 2019-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0021_auto_20190331_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/calcgen2/pressureVessel/static/reports/'),
        ),
    ]
