# Generated by Django 2.1.2 on 2019-04-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0024_report_projectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='author_id',
        ),
    ]
