# Generated by Django 2.1.2 on 2019-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0025_remove_report_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_state',
            field=models.FilePathField(allow_folders=True, default='baka', max_length=255, path='/home/calcgen2/pressureVessel/static/states/'),
            preserve_default=False,
        ),
    ]
