# Generated by Django 2.1.2 on 2019-04-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0026_report_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='orientation',
            field=models.CharField(default='vertical', max_length=100),
            preserve_default=False,
        ),
    ]
