# Generated by Django 2.2 on 2019-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0027_report_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='C:\\Users\\CALCGEN NEPAL 02\\Desktop\\sushil\\office\\pressure-vessel\\static/reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_state',
            field=models.FilePathField(allow_folders=True, max_length=255, path='C:\\Users\\CALCGEN NEPAL 02\\Desktop\\sushil\\office\\pressure-vessel\\static/states/'),
        ),
    ]
