# Generated by Django 2.1.2 on 2019-05-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0028_auto_20190527_0655'),
        ('reporter', '0028_auto_20190520_1039'),
    ]

    operations = [
    ]
