# Generated by Django 2.1.2 on 2019-06-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0029_merge_20190527_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/workspace/pressure-vessel/static/reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_state',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/home/sushil/Desktop/workspace/pressure-vessel/static/states/'),
        ),
    ]
