# Generated by Django 2.1.2 on 2019-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0030_auto_20190624_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/static/reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_state',
            field=models.FilePathField(allow_folders=True, max_length=255, path='/static/states/'),
        ),
    ]
