# Generated by Django 2.1.2 on 2019-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_auto_20190805_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcpolling_detail',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
