# Generated by Django 2.1.2 on 2019-08-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0003_oidcpolling_detail_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OIDCPolling_Detail',
        ),
    ]
