# Generated by Django 2.1.2 on 2019-07-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PressureVesselApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(max_length=50)),
                ('author', models.CharField(default='shovan', max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
