# Generated by Django 2.1.2 on 2019-03-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0002_auto_20190318_0714'),
        ('reporter', '0017_auto_20190318_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreOfGravity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CylinderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D', models.FloatField(default=0.0)),
                ('C_A', models.FloatField(default=0.0)),
                ('P', models.FloatField(default=0.0)),
                ('R', models.FloatField(default=0.0)),
                ('S', models.FloatField(default=0.0)),
                ('E', models.FloatField(default=0.0)),
                ('t_inter', models.FloatField(default=0.0)),
                ('t', models.FloatField(default=0.0)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='component.Component')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Report', verbose_name='the related report')),
            ],
        ),
        migrations.CreateModel(
            name='NozzleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
