# Generated by Django 2.1.2 on 2019-03-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_remove_component_material'),
        ('reporter', '0018_merge_20190324_0428'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzlestate',
            name='C_n',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='E',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='L_H',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='L_R',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='P',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='R_n',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='R_o',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='S_n',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='component',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='component.Component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='msg',
            field=models.TextField(default='fire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='report',
            field=models.ForeignKey(default=172, on_delete=django.db.models.deletion.CASCADE, to='reporter.Report', verbose_name='the related report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='t',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='t_e',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='t_n',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='t_r',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='t_rn',
            field=models.FloatField(default=0.0),
        ),
    ]
