# Generated by Django 2.1.2 on 2019-04-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_liftinglugstate_skirtstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftinglugstate',
            name='sigma_b',
            field=models.FloatField(default=0.0),
        ),
    ]
