# Generated by Django 2.1.2 on 2019-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_liftinglugstate_sigma_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzlestate',
            name='A_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nozzlestate',
            name='A_r',
            field=models.FloatField(default=0.0),
        ),
    ]
